- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_chache: yes
      changed_when: False

  tasks:
    - name: include tasks file
      ansible.builtin.include_tasks:
        file: tasks/packages.yml
