- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: include pakcages file
      ansible.builtin.include_tasks:
        file: tasks/packages.yml
    - name: include users file
      ansible.builtin.include_tasks:
        file: tasks/users.yml
    - name: include cron file
      ansible.builtin.include_tasks:
        file: tasks/cron.yml
